services:
  directus:
    image: directus/directus:latest
    ports:
      - "8055:8055"
    env_file:
      - .env
    environment:
      DB_CLIENT: "pg"
      DB_SSL__REJECT_UNAUTHORIZED: "false"
      DB_SSL__CA: ""
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      PUBLIC_URL: "http://localhost:8055"
