// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Uu9JFkm8RAMNOnYKqAUfbvDEVoswTCM',
    appId: '1:1028710749210:web:5b6be879e51ccccdb12da3',
    messagingSenderId: '1028710749210',
    projectId: 'outfitly-bccd3',
    authDomain: 'outfitly-bccd3.firebaseapp.com',
    databaseURL: 'https://outfitly-bccd3-default-rtdb.firebaseio.com',
    storageBucket: 'outfitly-bccd3.firebasestorage.app',
    measurementId: 'G-M29M74274M',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoMqKlnoIZ6Vt9F2bFk7M6WQDjH4-dQCc',
    appId: '1:1028710749210:ios:36d79ba8b73a7df3b12da3',
    messagingSenderId: '1028710749210',
    projectId: 'outfitly-bccd3',
    databaseURL: 'https://outfitly-bccd3-default-rtdb.firebaseio.com',
    storageBucket: 'outfitly-bccd3.firebasestorage.app',
    iosBundleId: 'com.outfitly.outfitly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6Uu9JFkm8RAMNOnYKqAUfbvDEVoswTCM',
    appId: '1:1028710749210:web:74e68da709bdd9d5b12da3',
    messagingSenderId: '1028710749210',
    projectId: 'outfitly-bccd3',
    authDomain: 'outfitly-bccd3.firebaseapp.com',
    databaseURL: 'https://outfitly-bccd3-default-rtdb.firebaseio.com',
    storageBucket: 'outfitly-bccd3.firebasestorage.app',
    measurementId: 'G-YGSE4WQBDQ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoMqKlnoIZ6Vt9F2bFk7M6WQDjH4-dQCc',
    appId: '1:1028710749210:ios:36d79ba8b73a7df3b12da3',
    messagingSenderId: '1028710749210',
    projectId: 'outfitly-bccd3',
    databaseURL: 'https://outfitly-bccd3-default-rtdb.firebaseio.com',
    storageBucket: 'outfitly-bccd3.firebasestorage.app',
    iosBundleId: 'com.outfitly.outfitly',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnTgXddE2-c7JeY7kQ1ZUN-L7BT2V39yI',
    appId: '1:1028710749210:android:929c8ec39d62d836b12da3',
    messagingSenderId: '1028710749210',
    projectId: 'outfitly-bccd3',
    databaseURL: 'https://outfitly-bccd3-default-rtdb.firebaseio.com',
    storageBucket: 'outfitly-bccd3.firebasestorage.app',
  );

}